import test from 'node:test';
import assert from 'node:assert/strict';
import { validateNaturalStrategy, runSplitOpportunity } from '../qa/StrategicBehaviorHarness.mjs';
import { makeScrambleQa } from '../qa/ScrambleSimulationHarness.mjs';
import { quiet } from '../qa/LivingCampSimulationHarness.mjs';
test('unforced production planner trajectories match JSON restore through multiple actual Tribals',()=>{const r=validateNaturalStrategy({families:['no-alliance','strong-majority'],seedsPerFamily:1,roundLimit:2});assert.equal(r.length,2);for(const x of r){assert.ok(x.saveLoadEquivalent);assert.equal(x.rounds.length,2);assert.ok(x.milestones.includes('after-first-strategic-conversation'));assert.ok(x.milestones.includes('immediately-before-Tribal'));assert.ok(x.rounds.every(t=>t.votes.length));}});
test('seven-person genuine five-two majority settles without repeated recruitment of supporters',()=>quiet(()=>{const s=makeScrambleQa({scenario:'clear-majority'}),m=s.strategy.reasoning,A=s.gm.systems.allianceSystem,people=s.activity.npcs(),target=people.at(-1);A.reset();s.memory.deserialize({});s.strategy.scramble.meetings=[];s.strategy.scramble.nextApproachAt=-1;s.idle();const group=people.slice(0,5),a=A.createAlliance({memberIds:group.map(p=>p.id),type:'core'});for(const p of group){s.strategy.updateNpcIntentTarget(p.id,target.id,{absoluteConfidence:.9});m.state(p.id).preferredTargetId=target.id;m.state(p.id).committedTargetId=target.id;}s.strategy.scramble.scheduleAlliances();while(s.gm.dayTimer>0)s.wait(60);const retained=group.filter(p=>String(m.state(p.id).intendedVoteId)===String(target.id)).length;assert.ok(retained>=4,`${retained}/5 majority votes held`);assert.equal(m.metrics.unnecessaryRecruitSwing||0,0);assert.equal(m.metrics.splitPlans||0,0);assert.equal(m.metrics.backups||0,0);assert.ok(s.strategy.scramble.meetings.some(meeting=>meeting.status==='completed'));assert.ok(m.metrics.settledPlansHeld>=0||retained===5);assert.ok(a.roundPlan.primaryTargetId!=null);}));

test('a viable idol-risk coalition autonomously gathers and proposes a split without a staged plan',()=>{const a=runSplitOpportunity(),b=runSplitOpportunity({reload:true});assert.deepEqual(b.projection,a.projection);assert.ok(a.metrics.splitPlans>=1);assert.equal(a.metrics.splitPlans,a.metrics.viableSplitPlans);assert.ok(a.splits.every(p=>Object.values(p.counts).every(n=>n>a.opposition)));assert.ok(a.meetings.some(x=>x.status==='completed'&&x.outcome?.outcome==='consensus'));});
