import test from 'node:test';
import assert from 'node:assert/strict';
import { makeScrambleQa } from '../qa/ScrambleSimulationHarness.mjs';
import { quiet } from '../qa/LivingCampSimulationHarness.mjs';
import { scrambleNodes, resolveScrambleNode } from '../src/modules/systems/ScrambleConversation.js';
import { campGroups } from '../src/modules/ui/CampPresentation.js';
const setup=()=>quiet(()=>{const s=makeScrambleQa();s.strategy.scramble.meetings=[];s.strategy.scramble.nextApproachAt=-1;s.idle();
 const [a,b,c,d]=s.activity.npcs();return {...s,a,b,c,d,get m(){return s.strategy.reasoning;},get memory(){return s.gm.systems.socialMemorySystem;}};});
const say=(s,overrides={})=>s.m.statement({id:'test:statement',speakerId:s.a.id,listenerIds:[s.b.id],subjectId:s.c.id,random:()=>0,...overrides});
const start=s=>{s.activity.beginConversation(s.a,{location:'beach',strategy:true});return s.activity.conversation;};
const nodes=(s,topic='strategy')=>scrambleNodes(s.m,{player:s.gm.player,npc:s.a,topic});

test('preference, actual vote, commitment and audience pitch are independent',()=>{const s=setup();s.m.state(s.a.id).preferredTargetId=s.d.id;
 s.strategy.updateNpcIntentTarget(s.a.id,s.c.id);say(s,{subjectId:s.d.id});assert.equal(s.m.state(s.a.id).intendedVoteId,s.c.id);
 assert.equal(s.m.state(s.a.id).preferredTargetId,s.d.id);assert.equal(s.m.state(s.a.id).committedTargetId,null);
 assert.equal(s.m.state(s.a.id).pitchesByAudience[s.b.id].subjectId,s.d.id);assert.equal(s.strategy.getNpcTargetIntent(s.a.id).targetId,s.c.id);});
test('rich state migrates old intent maps without inventing player intent',()=>{const s=setup(),payload=s.strategy.serialize();delete payload.strategic;s.strategy.deserialize(payload);
 assert.equal(s.m.state(s.a.id).intendedVoteId,s.strategy.npcIntentTargets.get(s.a.id));assert.equal(s.m.states[String(s.gm.player.id)],undefined);});
test('confidence and flexibility bounded using existing production traits',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.a.id,s.c.id,{absoluteConfidence:5});
 assert.equal(s.m.state(s.a.id).confidence,1);assert.ok(s.m.state(s.a.id).flexibility>=0&&s.m.state(s.a.id).flexibility<=1);});
for(const mode of ['truthful','hearsay','inference','speculation','deliberate_lie','decoy','reassurance_lie'])test(`statement ${mode} keeps audience knowledge and hidden truth separate`,()=>{
 const s=setup();say(s,{mode,attributedId:mode==='hearsay'?s.d.id:null});const b=s.memory.getCampClaims(s.b.id).find(e=>e.id==='test:statement');
 assert.ok(b);assert.equal(b.truthfulness,undefined);assert.ok(!('mode' in b));assert.equal(s.memory.getCampClaims(s.d.id).some(e=>e.id===b.id),false);
 assert.ok(s.m.knowledge(s.b.id).some(e=>e.id===b.id));if(mode==='hearsay')assert.equal(b.origin,'hearsay');
 if(['deliberate_lie','decoy','reassurance_lie'].includes(mode))assert.equal(s.memory.getCampClaims(s.a.id).find(e=>e.id===b.id).truthfulness,false);
});
test('direct statements and relayed accounts preserve original source chain',()=>{const s=setup();say(s);s.memory.shareCampClaim({fromId:s.b.id,toId:s.d.id,claimId:'test:statement'});
 const claim=s.memory.getCampClaims(s.d.id).find(e=>e.id==='test:statement');assert.equal(claim.origin,'hearsay');assert.equal(claim.sourceId,s.b.id);assert.ok(claim.sourceChain.includes(s.a.id));});
test('same-source contradictory plans create uncertainty without declaring truth',()=>{const s=setup();say(s);say(s,{id:'test:contrary',subjectId:s.d.id});
 assert.ok(s.m.contradictions(s.b.id).some(e=>e.id==='test:contrary'));assert.equal(s.memory.getCampClaims(s.b.id).find(e=>e.id==='test:contrary').truthfulness,undefined);});
test('convincing player lie can be believed without psychic trust penalty',()=>{const s=setup();const trust=s.gm.getTrust(s.b.id,s.gm.player.id);
 const result=say(s,{speakerId:s.gm.player.id,mode:'deliberate_lie',topic:'safety',subjectId:s.b.id,stance:'warned',attributedId:s.c.id});
 assert.equal(result.belief[s.b.id],true);assert.equal(s.gm.getTrust(s.b.id,s.gm.player.id),trust);assert.ok(s.m.state(s.b.id).safetyBelief<.7);});
test('implausible lie can remain uncertain without truth-based punishment',()=>{const s=setup();const trust=s.gm.getTrust(s.b.id,s.gm.player.id);
 const result=say(s,{speakerId:s.gm.player.id,mode:'deliberate_lie',random:()=>.999});assert.equal(result.belief[s.b.id],false);assert.equal(s.gm.getTrust(s.b.id,s.gm.player.id),trust);});
test('initial truthful and false delivery scores are identical',()=>{const s=setup(),input={subjectId:s.c.id,topic:'target',stance:'consider'};
 assert.equal(s.m.credibility(s.a,s.b,{...input,mode:'truthful'}),s.m.credibility(s.a,s.b,{...input,mode:'deliberate_lie'}));});
test('credible original-source denial can discredit relayer only for actual listener',()=>{const s=setup();say(s,{speakerId:s.gm.player.id,subjectId:s.b.id,topic:'safety',stance:'warned',mode:'deliberate_lie',attributedId:s.c.id});
 const before=s.memory.getCampSourceReliability(s.b.id,s.gm.player.id);say(s,{id:'test:denial',speakerId:s.c.id,subjectId:s.b.id,topic:'safety',stance:'denied',refutesClaimId:'test:statement'});
 assert.ok(s.memory.getCampSourceReliability(s.b.id,s.gm.player.id)<before);assert.equal(s.memory.getCampSourceReliability(s.d.id,s.gm.player.id),.75);});
test('false reassurance does not change the speaker private vote',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.a.id,s.b.id);
 say(s,{subjectId:s.b.id,topic:'safety',stance:'yes',mode:'reassurance_lie'});assert.equal(s.strategy.getNpcTargetIntent(s.a.id).targetId,s.b.id);});
test('decoy records hidden purpose only in speaker reality',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.a.id,s.c.id);s.m.decoy(s.a.id,s.d.id,[s.b.id],'flush_idol');
 const agenda=s.m.agenda(s.a.id,s.b.id);assert.equal(agenda.messageMode,'decoy');s.m.resolveAgenda(s.a,s.b,{id:'decoy',agenda},()=>0);
 assert.equal(s.strategy.getNpcTargetIntent(s.a.id).targetId,s.c.id);assert.equal(s.m.knowledge(s.b.id).find(e=>e.id==='decoy:agenda:'+s.b.id).subjectId,s.d.id);});
test('two honest contestants can have different owned vote reads',()=>{const s=setup();say(s);say(s,{id:'elsewhere',listenerIds:[s.d.id],subjectId:s.b.id});
 assert.equal(s.m.voteRead(s.b.id).targetId,s.c.id);assert.equal(s.m.voteRead(s.d.id).targetId,s.b.id);});
test('owned vote read can honestly be unknown despite global target board',()=>{const s=setup();s.strategy.computeTribalTargetBoard();assert.equal(s.m.voteRead(s.gm.player.id).targetId,null);});
test('vote-read rendering consumes no semantic time, randomness or strategic mutations',()=>{const s=setup();start(s);const before=JSON.stringify(s.m.serialize()),rng=s.strategy.scramble.rngState;
 for(let i=0;i<30;i++)nodes(s);assert.equal(JSON.stringify(s.m.serialize()),before);assert.equal(s.strategy.scramble.rngState,rng);assert.equal(s.gm.dayTimer,3600);});
test('owned commitments estimate viability without global intended votes',()=>{const s=setup();s.m.state(s.a.id).intendedVoteId=s.c.id;const initial=s.m.viability(s.a.id,s.c.id);
 for(const npc of s.activity.npcs())s.strategy.updateNpcIntentTarget(npc.id,s.c.id);assert.equal(s.m.viability(s.a.id,s.c.id),initial);
 s.m.commit({id:'promise',speakerId:s.b.id,listenerIds:[s.a.id],targetId:s.c.id,random:()=>0});assert.ok(s.m.viability(s.a.id,s.c.id)>initial);});
test('working-together answer never scans global relationship maxima',()=>{const s=setup();assert.equal(s.m.knownPair(s.d.id),null);
 s.memory.recordCampObservation({id:'pair',actorId:s.a.id,type:'seen_together',participantIds:[s.b.id],witnessIds:[s.d.id],location:'beach',day:s.gm.day,campTime:3500,visibility:'private'});
 assert.deepEqual(s.m.knownPair(s.d.id).ids,[s.a.id,s.b.id]);});
test('player recap is read-only and excludes hidden intent, truth flags and secret decoys',()=>{const s=setup();say(s,{listenerIds:[s.gm.player.id],mode:'decoy'});
 const before=JSON.stringify(s.m.serialize()),recap=s.m.recap();assert.equal(JSON.stringify(s.m.serialize()),before);
 assert.equal(recap.currentVoteIntent,null);assert.equal(JSON.stringify(recap).includes('truthfulness'),false);assert.equal(JSON.stringify(recap).includes('intendedVoteId'),false);});
test('contradictory player promises are legal and audience-scoped',()=>{const s=setup();s.m.commit({id:'one',speakerId:s.gm.player.id,listenerIds:[s.a.id],targetId:s.c.id,random:()=>0});
 s.m.commit({id:'two',speakerId:s.gm.player.id,listenerIds:[s.b.id],targetId:s.d.id,random:()=>0});assert.equal(s.m.state(s.gm.player.id).intendedVoteId,s.d.id);
 assert.equal(s.memory.getCampClaims(s.a.id).some(e=>e.id==='two'),false);assert.equal(s.m.recap().promises.length,2);});
test('informal promises do not create formal deals',()=>{const s=setup(),before=s.gm.systems.dealSystem.serialize();s.m.commit({id:'one',speakerId:s.a.id,listenerIds:[s.b.id],targetId:s.c.id,random:()=>0});
 assert.deepEqual(s.gm.systems.dealSystem.serialize(),before);assert.equal(s.m.state(s.a.id).committedTargetId,s.c.id);});
test('backup activation reaches informed participants only',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.c.id,s.a.id);s.strategy.updateNpcIntentTarget(s.b.id,s.c.id);s.m.backup(s.a.id,s.c.id,s.d.id,[s.b.id]);
 assert.equal(s.m.state(s.c.id).backup,null);assert.equal(s.m.activateBackup(s.c.id,'suspected_idol'),false);assert.equal(s.m.activateBackup(s.a.id,'suspected_idol'),true);
 assert.equal(s.strategy.getNpcTargetIntent(s.b.id).targetId,s.d.id);assert.equal(s.strategy.getNpcTargetIntent(s.c.id).targetId,s.a.id);});
test('backup does not activate on unrelated trigger',()=>{const s=setup();s.m.backup(s.a.id,s.c.id,s.d.id,[s.b.id]);assert.equal(s.m.activateBackup(s.a.id,'random_final_minutes'),false);});
test('split assignments preserve separate votes and partial knowledge',()=>{const s=setup();s.m.split(s.a.id,s.c.id,s.d.id,{[s.a.id]:s.c.id,[s.b.id]:s.d.id},[s.a.id]);
 assert.equal(s.m.state(s.b.id).splitPlan.primaryTargetId,undefined);s.m.acceptSplit(s.a.id);s.m.acceptSplit(s.b.id);
 assert.equal(s.strategy.getNpcTargetIntent(s.a.id).targetId,s.c.id);assert.equal(s.strategy.getNpcTargetIntent(s.b.id).targetId,s.d.id);});
test('one defection changes individual split math without forcing others',()=>{const s=setup();s.m.split(s.a.id,s.c.id,s.d.id,{[s.a.id]:s.c.id,[s.b.id]:s.d.id});s.m.acceptSplit(s.a.id);s.m.acceptSplit(s.b.id);
 s.strategy.updateNpcIntentTarget(s.b.id,s.c.id);assert.equal(s.m.state(s.b.id).splitPlan.assignedVoteId,s.d.id);assert.equal(s.strategy.getNpcTargetIntent(s.a.id).targetId,s.c.id);});
test('rich backup/split/preferences/promises survive production restore',()=>{const s=setup();s.m.backup(s.a.id,s.c.id,s.d.id,[s.b.id]);s.m.split(s.a.id,s.c.id,s.d.id,{[s.a.id]:s.c.id,[s.b.id]:s.d.id});
 s.m.commit({id:'commit',speakerId:s.a.id,listenerIds:[s.b.id],targetId:s.c.id,random:()=>0});const before=s.m.serialize();s.restore();assert.deepEqual(s.m.serialize(),before);});
test('travelers cannot receive destination strategy statements or groups',()=>{const s=setup();s.activity.start(s.b,{type:'travel',location:'waterWell',duration:45});
 s.activity.start(s.a,{type:'observe',location:'waterWell',duration:300});say(s);assert.equal(s.memory.getCampClaims(s.b.id).some(e=>e.id==='test:statement'),false);
 assert.equal(campGroups(s.gm,'waterWell').some(g=>g.members.some(p=>p.id===s.b.id)),false);});
test('in-transit player cannot receive destination statements',()=>{const s=setup();s.activity.start(s.gm.player,{type:'travel',location:'waterWell',external:true,duration:30});
 s.activity.start(s.a,{type:'observe',location:'waterWell',duration:300});say(s,{listenerIds:[s.gm.player.id]});assert.equal(s.memory.getCampClaims(s.gm.player.id).some(e=>e.id==='test:statement'),false);});
test('warning motive favors relevant threatened ally',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.a.id,s.d.id);s.gm.systems.trustSystem.changeTrust(s.a.id,s.b.id,30);
 say(s,{speakerId:s.c.id,listenerIds:[s.a.id],subjectId:s.b.id,topic:'safety',stance:'warned'});
 assert.equal(s.m.agenda(s.a.id,s.b.id).purpose,'warn_ally');assert.ok(s.m.candidateScore(s.a.id,s.b.id)>s.m.candidateScore(s.a.id,s.d.id));});
test('verification motive seeks alleged original source',()=>{const s=setup();say(s,{speakerId:s.c.id,listenerIds:[s.a.id],attributedId:s.b.id});
 assert.equal(s.m.agenda(s.a.id,s.b.id).purpose,'verify_story');assert.ok(s.m.candidateScore(s.a.id,s.b.id)>s.m.candidateScore(s.a.id,s.d.id));});
test('approach recency prevents one NPC monopolizing player',()=>{const s=setup();s.m.state(s.a.id).lastContacts[s.gm.player.id]=3600;
 assert.equal(s.m.candidateScore(s.a.id,s.gm.player.id),-Infinity);s.gm.dayTimer=3100;assert.ok(Number.isFinite(s.m.candidateScore(s.a.id,s.gm.player.id)));});
test('partner planner rejects travelers even when raw destination is correct',()=>{const s=setup();s.activity.start(s.b,{type:'travel',location:'beach',duration:45});assert.equal(s.m.choosePartner(s.a,[s.b]),null);});
test('positive acknowledgement can hedge without changing actual vote',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.b.id,s.d.id,{absoluteConfidence:.8});s.m.state(s.b.id).committedTargetId=s.d.id;
 const outcome=s.m.adoption(s.b.id,s.a.id,s.c.id,{belief:false,random:()=>0});assert.ok(['hedge','refuse','open'].includes(outcome));assert.equal(s.strategy.getNpcTargetIntent(s.b.id).targetId,s.d.id);});
test('alliance gathering keeps personal preferences and can disagree',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.a.id,s.c.id);s.strategy.updateNpcIntentTarget(s.b.id,s.d.id);
 s.m.state(s.a.id).preferredTargetId=s.c.id;s.m.state(s.b.id).preferredTargetId=s.d.id;const result=s.m.resolveMeeting([s.a,s.b],{id:'meeting'},()=>.99);
 assert.equal(result.positions.length,2);assert.equal(s.m.state(s.a.id).preferredTargetId,s.c.id);assert.equal(s.m.state(s.b.id).preferredTargetId,s.d.id);assert.equal(result.outcome,'disagreement');});
test('each alliance member contributes a position rather than single-speaker overwrite',()=>{const s=setup();s.m.resolveMeeting([s.a,s.b,s.c],{id:'meeting'},()=>.99);
 for(const p of [s.a,s.b,s.c])assert.ok(s.memory.getCampClaims(p.id).some(e=>e.id===`meeting:position:${p.id}`));});
test('final minutes increase urgency without a random target reroll',()=>{const s=setup();const target=s.strategy.getNpcTargetIntent(s.a.id).targetId,early=s.m.refresh(s.a.id).urgency;
 s.gm.dayTimer=480;assert.ok(s.m.refresh(s.a.id).urgency>early);assert.equal(s.strategy.getNpcTargetIntent(s.a.id).targetId,target);});
test('idol possession uses usable inventory even without legacy flag',()=>{const s=setup();s.a.hasIdol=false;s.gm.systems.idolSystem.survivorInventories.set(s.a.id,{idols:[{id:'actual',isUsed:false}]});assert.equal(s.m.idolAnswer(s.a.id).ownsIdol,true);});
test('idol search answer uses actual history rather than random fact creation',()=>{const s=setup();start(s);assert.equal(s.m.searched(s.a.id),false);
 s.gm.systems.idolSystem.searchHistory.set(String(s.a.id),{count:1,day:s.gm.day,location:'jungleTrail'});assert.equal(s.m.searched(s.a.id),true);
 const node=nodes(s,'idol').find(n=>n.id==='idol_looked'),result=resolveScrambleNode(s.m,node,s.a.id);assert.equal(resolveScrambleNode(s.m,node,s.a.id).line,result.line);assert.equal(s.m.searched(s.a.id),true);});
test('search history survives new camp phase and save restoration',()=>{const s=setup();s.gm.systems.idolSystem.searchHistory.set(String(s.a.id),{count:2});s.gm.systems.idolSystem.startNewCampPhase();s.restore();assert.equal(s.m.searched(s.a.id),true);});
test('idol hearsay never promotes itself into actual possession',()=>{const s=setup();say(s,{topic:'idol_suspicion',stance:'possible'});s.memory.shareCampClaim({fromId:s.b.id,toId:s.d.id,claimId:'test:statement'});
 assert.equal(s.m.idolAnswer(s.c.id).ownsIdol,false);assert.equal(s.m.knowledge(s.d.id).find(e=>e.id==='test:statement').provenance,'hearsay');});
test('context nodes never invent evidence-specific confrontation',()=>{const s=setup();start(s);assert.ok(nodes(s,'confront').every(n=>n.id.startsWith('bluff_warning')));
 say(s,{listenerIds:[s.gm.player.id],subjectId:s.gm.player.id,topic:'safety',stance:'warned'});assert.ok(nodes(s,'confront').some(n=>n.id.startsWith('confront:')));});
test('contextual pitch uses checkpoint semantic RNG without replay',()=>{const s=setup();const reservation=start(s),node=nodes(s).find(n=>n.id.startsWith('counter:'));
 const result=resolveScrambleNode(s.m,node,s.a.id),before=s.m.serialize();assert.ok(result.line);assert.equal(resolveScrambleNode(s.m,node,s.a.id).replay,true);
 assert.deepEqual(s.m.serialize(),before);assert.equal(reservation.checkpoint.turnCount,1);});
test('reload after two meaningful choices retains outcomes once and charges time once',()=>{const s=setup();start(s);const first=nodes(s).find(n=>n.id.startsWith('bluff_warning:')),second=nodes(s).find(n=>n.id.startsWith('commit:'));
 resolveScrambleNode(s.m,first,s.a.id);resolveScrambleNode(s.m,second,s.a.id);const before=s.m.serialize(),cp=JSON.stringify(s.activity.conversation.checkpoint);
 s.restore();for(const id of [first.id,second.id])assert.equal(resolveScrambleNode(s.m,nodes(s).find(n=>n.id===id),s.a.id).replay,true);
 assert.deepEqual(s.m.serialize(),before);assert.equal(JSON.stringify(s.activity.conversation.checkpoint),cp);assert.equal(s.gm.dayTimer,3600);
 s.activity.finishConversation({strategy:true});const charged=s.gm.dayTimer;assert.ok(charged<3600);s.activity.finishConversation({strategy:true});assert.equal(s.gm.dayTimer,charged);});
test('save before identical choice cannot reroll outcome',()=>{const s=setup();start(s);const save=JSON.parse(JSON.stringify(s.gm.createSavePayload()));const id=nodes(s).find(n=>n.id.startsWith('counter:')).id;
 const one=resolveScrambleNode(s.m,nodes(s).find(n=>n.id===id),s.a.id);quiet(()=>s.gm.restoreSavePayload(save));const two=resolveScrambleNode(s.m,nodes(s).find(n=>n.id===id),s.a.id);assert.deepEqual(two,one);});
test('checkpoint contains semantic fields without DOM/dialog state',()=>{const s=setup();start(s);resolveScrambleNode(s.m,nodes(s)[0],s.a.id);const cp=s.activity.conversation.checkpoint;
 assert.equal(cp.activityId,s.activity.conversation.activityId);assert.ok(cp.choices);assert.ok(cp.statementIds);assert.equal(JSON.stringify(cp).includes('<div'),false);assert.equal(cp.focus,undefined);});
test('duplicate promise IDs cannot duplicate state, facts or memory',()=>{const s=setup(),args={id:'promise',speakerId:s.a.id,listenerIds:[s.b.id],targetId:s.c.id,random:()=>0};s.m.commit(args);const before=s.m.serialize(),facts=s.strategy.strategyFacts.length;
 s.m.commit(args);assert.deepEqual(s.m.serialize(),before);assert.equal(s.strategy.strategyFacts.length,facts);});
test('immune targets remain invalid for actual intent, backups and split',()=>{const s=setup(),old=s.gm.hasImmunity;s.gm.hasImmunity=p=>p?.id===s.c.id;
 try{assert.equal(s.strategy.updateNpcIntentTarget(s.a.id,s.c.id),null);assert.equal(s.m.backup(s.a.id,s.b.id,s.c.id),null);assert.equal(s.m.split(s.a.id,s.c.id,s.d.id,{[s.a.id]:s.c.id}),null);}finally{s.gm.hasImmunity=old;}});
test('backup and split interaction options require actual group reservation',()=>{const s=setup();start(s);assert.equal(nodes(s).some(n=>n.id.startsWith('split_vote:')),false);
 s.activity.reserveConversationGroup([s.b.id,s.c.id]);say(s,{listenerIds:[s.gm.player.id],subjectId:s.d.id});assert.ok(nodes(s).some(n=>n.id.startsWith('split_vote:')));assert.ok(nodes(s).some(n=>n.id.startsWith('backup:')));});
test('player group split is a proposal, preserves optional player vote and individual states',()=>{const s=setup();start(s);s.activity.reserveConversationGroup([s.b.id,s.c.id]);const pref=s.m.state(s.b.id).preferredTargetId;say(s,{listenerIds:[s.gm.player.id],subjectId:s.d.id});
 const node=nodes(s).find(n=>n.id.startsWith('split_vote:'));resolveScrambleNode(s.m,node,s.a.id);assert.ok(s.m.state(s.gm.player.id).splitPlan);
 assert.equal(s.m.state(s.gm.player.id).intendedVoteId,null);assert.equal(s.m.state(s.b.id).preferredTargetId,pref);});
test('live formal deal is idempotent after restore and does not duplicate alliances',()=>{const s=setup();start(s);s.conversation._renderMenu=()=>{};s.conversation._getActiveTranscriptSession=()=>({addNpc(){}});
 s.conversation._createDeal({player:s.gm.player,npc:s.a,dealType:'protect',target:null,status:'accepted'});
 const deals=s.gm.systems.dealSystem.serialize(),alliances=s.gm.systems.allianceSystem.serialize();s.restore();
 s.conversation._createDeal({player:s.gm.player,npc:s.a,dealType:'protect',target:null,status:'accepted'});assert.deepEqual(s.gm.systems.dealSystem.serialize(),deals);assert.deepEqual(s.gm.systems.allianceSystem.serialize(),alliances);});
test('formal strategic offer RNG is stable across restore before same choice',()=>{const s=setup();start(s);const saved=JSON.parse(JSON.stringify(s.gm.createSavePayload()));const one=s.conversation._scrambleRandom('deal:protect');
 quiet(()=>s.gm.restoreSavePayload(saved));assert.equal(s.conversation._scrambleRandom('deal:protect'),one);});
test('traveling intended listener cannot be reserved as a conversation partner',()=>{const s=setup();s.activity.start(s.b,{type:'travel',location:'beach',duration:45});
 s.activity.start(s.a,{type:'strategy_conversation',targetId:s.b.id,location:'beach',duration:240});assert.equal(s.a.campActivity.type,'observe');assert.equal(s.b.campActivity.type,'travel');});
test('old hidden strategy beat remains inert after rich state implementation',()=>{const s=setup(),before=JSON.stringify(s.m.serialize());for(let i=0;i<10;i++){s.strategy.runStrategyBeat();s.strategy.triggerNpcScramble();}
 assert.equal(JSON.stringify(s.m.serialize()),before);});
test('pre-immunity intelligence remains outside post-immunity adapter',()=>{const s=setup();s.gm.gamePhase='preChallenge';assert.equal(s.conversation._scrambleModel(),null);assert.ok(s.conversation._buildStrategyNodes({player:s.gm.player,npc:s.a,context:{}}).some(n=>n.id==='pitch_target'));});
test('safe tribe conversations do not create post-immunity strategic agenda',()=>{const s=setup();s.strategy.playerTribeSafe=true;assert.equal(s.conversation._scrambleModel(),null);});
test('same strategic statement id cannot multiply beliefs or commitments',()=>{const s=setup();const one=say(s),before=s.m.serialize();assert.deepEqual(say(s,{random:()=>.99}),one);assert.deepEqual(s.m.serialize(),before);});
test('late backup invalidated by immunity never creates an illegal vote',()=>{const s=setup();s.m.backup(s.a.id,s.c.id,s.d.id,[s.b.id]);const old=s.gm.hasImmunity;s.gm.hasImmunity=p=>p?.id===s.d.id;
 try{assert.equal(s.m.activateBackup(s.a.id,'suspected_idol'),false);}finally{s.gm.hasImmunity=old;}});
test('new owned idol suspicion can activate a known backup at planning boundary',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.b.id,s.c.id);s.m.backup(s.a.id,s.c.id,s.d.id,[s.b.id]);assert.equal(s.m.react(s.a.id),false);
 say(s,{speakerId:s.c.id,listenerIds:[s.a.id],topic:'idol_suspicion',stance:'possible'});assert.equal(s.m.react(s.a.id),true);assert.equal(s.strategy.getNpcTargetIntent(s.b.id).targetId,s.d.id);});
test('an uninformed NPC does not react to someone else backup knowledge',()=>{const s=setup();s.m.backup(s.a.id,s.c.id,s.d.id,[s.b.id]);say(s,{speakerId:s.b.id,listenerIds:[s.c.id],topic:'idol_suspicion',subjectId:s.a.id,stance:'possible'});
 assert.equal(s.m.react(s.c.id),false);});
test('warning and reassurance statements remain distinct from target pitches',()=>{const s=setup();say(s,{topic:'safety',stance:'warned'});assert.equal(s.m.voteRead(s.b.id).targetId,null);
 assert.ok(s.strategy.strategyFacts.some(e=>e.type==='strategicStatement'&&e.statementTopic==='safety'));});
test('human reading does not advance a reserved semantic conversation',async()=>{const s=setup();start(s);const before=s.gm.dayTimer;await new Promise(resolve=>setTimeout(resolve,5));
 assert.equal(s.gm.dayTimer,before);assert.equal(s.a.campActivity.type,'strategy_conversation_player');});
test('all eleven production-cast scenarios match interrupted production restore',async()=>{const {validateIntelligenceHarness}=await import('../qa/StrategicIntelligenceHarness.mjs');
 const reports=validateIntelligenceHarness();assert.equal(reports.length,11);assert.ok(reports.every(r=>r.saveLoadEquivalent&&r.semanticMinutes===60));});
test('backup trigger cannot telepathically notify an informed ally across camp',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.b.id,s.c.id);s.m.backup(s.a.id,s.c.id,s.d.id,[s.b.id]);
 s.activity.start(s.b,{type:'observe',location:'waterWell',duration:300});s.m.activateBackup(s.a.id,'suspected_idol');
 assert.equal(s.strategy.getNpcTargetIntent(s.b.id).targetId,s.c.id);assert.equal(s.m.state(s.b.id).backup.active,false);});
test('knowing a backup does not erase an unrelated individual plan',()=>{const s=setup();s.strategy.updateNpcIntentTarget(s.b.id,s.a.id);s.m.backup(s.a.id,s.c.id,s.d.id,[s.b.id]);s.m.activateBackup(s.a.id,'suspected_idol');
 assert.equal(s.strategy.getNpcTargetIntent(s.b.id).targetId,s.a.id);});
test('no actual commitment can be made to an immune target',()=>{const s=setup(),old=s.gm.hasImmunity;s.gm.hasImmunity=p=>p?.id===s.c.id;
 try{assert.equal(s.m.commit({id:'immune',speakerId:s.a.id,listenerIds:[s.b.id],targetId:s.c.id}),null);assert.equal(s.memory.getCampClaims(s.b.id).some(e=>e.id==='immune'),false);}finally{s.gm.hasImmunity=old;}});
test('player group proposals cannot use a hidden NPC intended vote as their primary',()=>{const s=setup();start(s);s.activity.reserveConversationGroup([s.b.id,s.c.id]);
 assert.equal(nodes(s).some(n=>n.id.startsWith('split_vote:')),false);const backup=nodes(s).find(n=>n.id.startsWith('backup:'));const result=resolveScrambleNode(s.m,backup,s.a.id);
 assert.equal(s.m.state(s.gm.player.id).backup,null);assert.ok(result.line.includes('main name'));});
