// Explicit resolver coverage, independent of the UI capability catalog. Each
// action has exactly one owner; adding a menu definition cannot invent behavior.
export const CONVERSATION_HANDLERS = Object.freeze({
  bond: [
    "check_in",
    "personal",
    "share_personal",
    "joke",
    "praise",
    "encourage",
    "comfort",
    "help",
    "spend_time",
  ],
  read: [
    "dangerous",
    "trustworthy",
    "lazy",
    "suspicious",
    "close",
    "isolated",
    "leader",
    "person_read",
    "vibe",
  ],
  information: ["share", "leak", "idol_rumor"],
  negotiate: ["pitch", "ask_vote", "press", "negotiate"],
  promise: ["promise", "conditional", "cover_promise", "withdraw"],
  plan: ["backup", "split"],
  deception: [
    "decoy",
    "bluff",
    "speculate",
    "leak_test",
    "idol_speculate",
    "idol_fabricate",
  ],
  task: ["delegate", "bring", "follow_task", "report"],
  secrecy: ["secrecy"],
  event: ["apologize", "repair", "confront", "admit", "deny", "event"],
  pressure: ["threaten"],
  agreement: ["deal", "idol_protect"],
  inventory: [
    "idol_reveal",
    "idol_hint",
    "idol_deny",
    "idol_conceal",
    "idol_bluff",
  ],
  question: [
    "idol_ask",
    "idol_search",
    "vote_read",
    "safety",
    "numbers",
    "verify",
    "source",
    "why",
    "evidence",
    "who_knows",
    "loyalty",
    "reassure",
    "warn",
  ],
  alliance: ["alliance", "person_include", "person_exclude"],
});
export const CONVERSATION_RESOLVER_TYPES = Object.values(
  CONVERSATION_HANDLERS,
).flat();
